name: CI
on: { pull_request: { } }
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - name: Build container
        uses: infrabits/ci-pack@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          use_builder: latest
