name: CI
on: { pull_request: { } }
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Build container
        uses: infrabits/ci-pack@e6fda6bd38b30aed25d3203d7559b756d75d884c # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          use_builder: latest
